### ISSUE TITLE
bro

### ISSUE THREAD

**Issue by V-erg** [MeatorJam/Discord-Image-Logger-WORKING-2023#1]
can you get out of my discord accounts.

**Comment by skatoss** [comment]
its a token grabber ?
or a malware ?

**Comment by V-erg** [comment]
> its a token grabber ? or a malware ?

Yes its a token grabber dualhook with luna grabber source code. Do not donwload or run this file.

**Comment by V-erg** [comment]
> its a token grabber ? or a malware ?

All of his repos r token grabbers. Not just tokens, everything from ur emails to credit cards saved on ur device.

**Comment by MeatorJam** [comment]
> > its a token grabber ? or a malware ?
> 
> Yes its a token grabber dualhook with luna grabber source code. Do not donwload or run this file.

huh? No it isn't I can send images if u want.
